-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 22:35:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdcoyuntura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcoyuntura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcoyuntura` DEFAULT CHARACTER SET utf8 ;
USE `bdcoyuntura` ;

-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Fuente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Fuente` (
  `idFuente` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idFuente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Variable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Variable` (
  `idVariable` INT NOT NULL AUTO_INCREMENT,
  `idFuente` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(1000) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVariable`),
  INDEX `Variable_Fuente_idx` (`idFuente` ASC),
  CONSTRAINT `Variable_Fuente`
    FOREIGN KEY (`idFuente`)
    REFERENCES `bdcoyuntura`.`Fuente` (`idFuente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`SuperCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`SuperCategoria` (
  `idSuperCategoria` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idSuperCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `idSuperCategoria` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `Categoria_SuperCategoria_idx` (`idSuperCategoria` ASC),
  CONSTRAINT `Categoria_SuperCategoria`
    FOREIGN KEY (`idSuperCategoria`)
    REFERENCES `bdcoyuntura`.`SuperCategoria` (`idSuperCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Ambito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Ambito` (
  `idAmbito` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idAmbito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`VariableAmbitoCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`VariableAmbitoCategoria` (
  `idVariable` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idAmbito` INT NOT NULL,
  `Mes` INT NOT NULL,
  `Year` INT NOT NULL,
  `Valor` FLOAT NULL,
  INDEX `VAC_Categoria_idx` (`idCategoria` ASC),
  INDEX `VAC_Variable_idx` (`idVariable` ASC),
  INDEX `VAC_Ambito_idx` (`idAmbito` ASC),
  CONSTRAINT `VAC_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdcoyuntura`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VAC_Variable`
    FOREIGN KEY (`idVariable`)
    REFERENCES `bdcoyuntura`.`Variable` (`idVariable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VAC_Ambito`
    FOREIGN KEY (`idAmbito`)
    REFERENCES `bdcoyuntura`.`Ambito` (`idAmbito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
