-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 19:46:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdcoyuntura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcoyuntura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcoyuntura` DEFAULT CHARACTER SET utf8 ;
USE `bdcoyuntura` ;

-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Variable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Variable` (
  `idVariable` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVariable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `idVariable` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `Categoria_Variable_idx` (`idVariable` ASC),
  CONSTRAINT `Categoria_Variable`
    FOREIGN KEY (`idVariable`)
    REFERENCES `bdcoyuntura`.`Variable` (`idVariable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Subcategoria` (
  `idSubcategoria` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idSubcategoria`),
  INDEX `Subcategoria_Categoria_idx` (`idCategoria` ASC),
  CONSTRAINT `Subcategoria_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdcoyuntura`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Ambito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Ambito` (
  `idAmbito` INT NOT NULL AUTO_INCREMENT,
  `idPais` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idAmbito`),
  INDEX `Ambito_Pais_idx` (`idPais` ASC),
  CONSTRAINT `Ambito_Pais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdcoyuntura`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`VariableAmbito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`VariableAmbito` (
  `idVariable` INT NOT NULL,
  `idAmbito` INT NOT NULL,
  `Trimestre` INT NOT NULL,
  `Año` INT NOT NULL,
  `Mes` INT NOT NULL,
  `Valor` INT NOT NULL,
  INDEX `Variable_Ambito_idx` (`idAmbito` ASC),
  INDEX `VariableAmbito_Variable_idx` (`idVariable` ASC),
  CONSTRAINT `VariableAmbito_Ambito`
    FOREIGN KEY (`idAmbito`)
    REFERENCES `bdcoyuntura`.`Ambito` (`idAmbito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VariableAmbito_Variable`
    FOREIGN KEY (`idVariable`)
    REFERENCES `bdcoyuntura`.`Variable` (`idVariable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoyuntura`.`Fuente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoyuntura`.`Fuente` (
  `idVariable` INT NOT NULL,
  `idAmbito` INT NOT NULL,
  `Fuente` VARCHAR(200) NOT NULL,
  INDEX `Fuente_Ambito_idx` (`idAmbito` ASC),
  INDEX `Fuente_Variable_idx` (`idVariable` ASC),
  CONSTRAINT `Fuente_Ambito`
    FOREIGN KEY (`idAmbito`)
    REFERENCES `bdcoyuntura`.`Ambito` (`idAmbito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fuente_Variable`
    FOREIGN KEY (`idVariable`)
    REFERENCES `bdcoyuntura`.`Variable` (`idVariable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
